DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "sessions";
DROP TABLE IF EXISTS "categories";
DROP TABLE IF EXISTS "posts";
DROP TABLE IF EXISTS "comments";

DROP TABLE IF EXISTS "messages";
DROP TABLE IF EXISTS "chats";

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid TEXT UNIQUE NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    nickname TEXT NOT NULL UNIQUE,
    gender TEXT CHECK(gender IN ('Male', 'Female', 'Other')) NOT NULL,
    age INTEGER NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    session_token TEXT UNIQUE, 
    session_expiry DATETIME, 
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_activity DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sessions (
    id UUID PRIMARY KEY,
    user_id INTEGER NOT NULL,
    is_active BOOLEAN NOT NULL,
    session_token TEXT NOT NULL UNIQUE,
    session_expiry DATETIME NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE categories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    emoji TEXT NOT NULL UNIQUE
);

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    categories TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE comments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    user_name TEXT NOT NULL,
    post_id INTEGER NOT NULL,
    content TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);

CREATE TABLE chats (
    "id" INTEGER PRIMARY KEY,
    "uuid" TEXT NOT NULL UNIQUE,
    "user_id_1" INTEGER NOT NULL,
    "user_id_2" INTEGER NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME,
    "updated_by" INTEGER,
    FOREIGN KEY (user_id_1) REFERENCES "users" ("id") ON DELETE CASCADE,
    FOREIGN KEY (user_id_2) REFERENCES "users" ("id") ON DELETE CASCADE,
    FOREIGN KEY (updated_by) REFERENCES "users" ("id") ON DELETE CASCADE,
    UNIQUE (user_id_1, user_id_2) 
);

CREATE TABLE messages (
    "id" INTEGER PRIMARY KEY,
    "chat_id" INTEGER NOT NULL,
    "user_id_from" INTEGER NOT NULL,
    "content" TEXT NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME,
    FOREIGN KEY (chat_id) REFERENCES "chats" ("id") ON DELETE CASCADE,
    FOREIGN KEY (user_id_from) REFERENCES "users" ("id") ON DELETE CASCADE
);

-------------------- Insert sample data into the database------------------------------------------------
-- Insert categories
INSERT INTO categories (name, emoji) VALUES
('Action', '💥'), ('Adventure', '🌄'), ('Animation', '🧚'), 
('Biography', '📚'), ('Comedy', '😂'), ('Crime', '🕵️'), ('Documentary', '🎥'), 
('Drama', '🎭'), ('Fantasy', '🧙'), ('Horror', '👻'), ('Mystery', '🔍'), 
('Romance', '❤️'), ('Sci-Fi', '🚀'), ('Thriller', '😱'), ('Western', '🤠');

-- Insert users
INSERT INTO users (uuid, nickname, email, password_hash, first_name, last_name, gender, age, created_at) VALUES
('550e8400-e29b-41d4-a716-446655440000', 'admin', 'admin@admin.com', '$2a$10$ryPUUMn0CPeuNh.NpQZOwuyoymt1sdzXrePhSeYArwv9puWlg1mF2', 'Admin', 'User', 'Male', 30, CURRENT_TIMESTAMP),
('6ba7b810-9dad-11d1-80b4-00c04fd430c0', 'Mama', 'mama@yahoo.com', '$2a$10$bfVNqrSBscGyfsGMSyEvaOCRbBbC54I2Lht5XuaBLiZKcdgoIRJQO', 'Mama', 'User', 'Female', 35, CURRENT_TIMESTAMP),
('6ba7b811-9dad-11d1-80b4-00c04fd430c1', 'batman', 'batman@batman.com', '$2a$10$1ZAK4MxQuwCJZGqhpBBzPOMoDDeGob..uwEIIO9YsHpqx8qXPNH8u', 'Bruce', 'Wayne', 'Male', 40, CURRENT_TIMESTAMP);


-- Insert posts
INSERT INTO posts (title, content, user_id, categories, created_at) VALUES
('The Thrilling Ride of "Quantum Horizon"', 'Quantum Horizon blends cutting-edge effects with a gripping narrative. The zero-gravity fights are breathtaking.', 2, 'Sci-Fi 🚀,Action 💥,Thriller 😱', CURRENT_TIMESTAMP),
('Laughing Through Time: A Hilarious Adventure', 'A refreshing take on time-travel comedy. Clever writing and impeccable timing had me in stitches.', 1, 'Comedy 😂,Adventure 🌄,Sci-Fi 🚀', CURRENT_TIMESTAMP),
('Whispers of the West: A Haunting Frontier Tale', 'This unconventional Western infuses horror into a frontier setting. Eerie atmosphere keeps viewers on edge.', 3, 'Western 🤠,Horror 👻,Mystery 🔍', CURRENT_TIMESTAMP),
('Brushstrokes of Genius: A Compelling Artist''s Biography', 'A meticulously crafted documentary about painter Isabella Rossi. Balances interviews with stunning visuals of her work.', 2, 'Documentary 🎥,Biography 📚', CURRENT_TIMESTAMP);

-- Insert comments for existing posts
INSERT INTO comments (post_id, content, user_id, user_name, created_at) VALUES
(1, 'This is an amazing post about Quantum Horizon!', 2, 'Mama', CURRENT_TIMESTAMP),
(2, 'Laughing Through Time is a masterpiece!', 1, 'admin', CURRENT_TIMESTAMP),
(3, 'Whispers of the West is so hauntingly beautiful.', 3, 'batman', CURRENT_TIMESTAMP),
(4, 'Brushstrokes of Genius is truly inspiring.', 2, 'Mama', CURRENT_TIMESTAMP);

-- Insert replies to comments (Note: your schema doesn't support nested comments, so these are additional comments on the same posts)
INSERT INTO comments (post_id, content, user_id, user_name, created_at) VALUES
(1, 'I completely agree with you, Mama!', 3, 'batman', CURRENT_TIMESTAMP),
(2, 'Admin, you have a great taste in comedy!', 2, 'Mama', CURRENT_TIMESTAMP),
(3, 'Batman, I felt the same way about the eerie atmosphere.', 1, 'admin', CURRENT_TIMESTAMP),
(4, 'Mama, the visuals were breathtaking indeed.', 3, 'batman', CURRENT_TIMESTAMP);


-- Additional comments with more discussion
INSERT INTO comments (post_id, content, user_id, user_name, created_at) VALUES
(1, 'The special effects in Quantum Horizon were mind-blowing!', 1, 'admin', CURRENT_TIMESTAMP),
(1, 'I thought the plot was a bit confusing in the middle.', 3, 'batman', CURRENT_TIMESTAMP),
(2, 'The time travel paradoxes were actually well-explained.', 3, 'batman', CURRENT_TIMESTAMP),
(2, 'I laughed so hard at the dinosaur scene!', 2, 'Mama', CURRENT_TIMESTAMP),
(3, 'The soundtrack really enhanced the creepy atmosphere.', 2, 'Mama', CURRENT_TIMESTAMP),
(3, 'I could not sleep after watching this!', 1, 'admin', CURRENT_TIMESTAMP),
(4, 'I did not know much about Isabella Rossi before this.', 3, 'batman', CURRENT_TIMESTAMP),
(4, 'Her use of color is revolutionary.', 1, 'admin', CURRENT_TIMESTAMP);


-- Insert sample chat data
-- INSERT INTO chats (uuid, user_id_1, user_id_2)
-- VALUES ('2586ead4-20d8-40cd-9310-64f75c26a18e', 2, 3);

-- INSERT INTO messages (chat_id, user_id_from, content) VALUES
-- (1, 2, 'How do you… how do you like my lawn club for St. Lou?'),
-- (1, 3, 'Hey, all those people gonna be at the game today?'),
-- (1, 2, 'Certainly'),
-- (1, 3, 'Ah, this is gonna be a whopper of a game!'),
-- (1, 2, 'Well it should be'),
-- (1, 3, 'Hey, 1…'),
-- (1, 2, 'What?'),
-- (1, 3, 'I understand they made you the manager of this here whole great team'),
-- (1, 2, 'Why not?'),
-- (1, 3, 'So, you the manager?'),
-- (1, 2, 'I''m the manager!'),
-- (1, 3, 'Well, you know, I''d like to know some of the guys'' names on the team so when I meet ''em on the street or in the ballpark I''ll be able to say, "Hello" to those people'),
-- (1, 2, 'Why sure I''ll introduce you to the boys. They give ''em funny names though'),
-- (1, 3, 'Oh I know they give those ball players awful funny names'),
-- (1, 2, 'Well, let''s see, on the team we have uh Who''s on first, What''s on second, I Don''t Know is on third…'),
-- (1, 3, 'Are you the manager?'),
-- (1, 2, 'Yes'),
-- (1, 3, 'You know the guys'' names?'),
-- (1, 2, 'I sure do'),
-- (1, 3, 'Then tell me the guys'' names'),
-- (1, 2, 'I say, Who''s on first, What''s on second, I Don''t Know''s on third and then you…'),
-- (1, 3, 'You the manager?'),
-- (1, 2, 'Yes'),
-- (1, 3, 'You know the guys'' names?'),
-- (1, 2, 'I''m telling you their names!'),
-- (1, 3, 'Well who''s on first?'),
-- (1, 2, 'Yeah'),
-- (1, 3, 'Go ahead and tell me'),
-- (1, 2, 'Who'),
-- (1, 3, 'The guy on first'),
-- (1, 2, 'Who'),
-- (1, 3, 'The guy playin'' first base'),
-- (1, 2, 'Who'),
-- (1, 3, 'The guy on first'),
-- (1, 2, 'Who is on first!'),
-- (1, 3, 'What are you askin'' me for? I''m askin'' you!'),
-- (1, 2, 'I''m not asking you, I''m telling you'),
-- (1, 3, 'You ain''t tellin'' me nothin''. I''m askin'' you, who''s on first?'),
-- (1, 2, 'That''s it!'),
-- (1, 3, 'Well go ahead and tell me!'),
-- (1, 2, 'Who!'),
-- (1, 3, 'The guy on first base'),
-- (1, 2, 'That''s his name'),
-- (1, 3, 'That''s whose name?'),
-- (1, 2, 'Yes'),
-- (1, 3, 'Well go ahead and tell me'),
-- (1, 2, 'That''s the man''s name!'),
-- (1, 3, 'That''s whose name?'),
-- (1, 2, 'Yeah!'),
-- (1, 3, 'Well go ahead and tell me!'),
-- (1, 2, 'Who is on first'),
-- (1, 3, 'What are you askin'' me for? I''m askin'' you, who''s on first?'),
-- (1, 2, 'That''s it'),
-- (1, 3, 'Well go ahead and tell me'),
-- (1, 2, 'Who'),
-- (1, 3, 'The guy on first'),
-- (1, 2, 'That''s it'),
-- (1, 3, 'What''s the guy''s name on first?'),
-- (1, 2, 'No, What''s on second'),
-- (1, 3, 'I''m not askin'' you who''s on second!'),
-- (1, 2, 'Who''s on first'),
-- (1, 3, 'That''s what I''m askin'' you! Who''s on first?'),
-- (1, 2, 'Now wait a minute. Don''t…don''t change the players'),
-- (1, 3, 'I''m not changin'' nobody! I asked you a simple question. What''s the guys'' name on first base?'),
-- (1, 2, 'What''s the guy''s name on second base'),
-- (1, 3, 'I''m not askin'' you who''s on second!'),
-- (1, 2, 'Who''s on first'),
-- (1, 3, 'I don''t know'),
-- (1, 2, 'He''s on third. Now we''re not talking about him'),
-- (1, 3, 'Look, you got a first baseman?'),
-- (1, 2, 'Yes'),
-- (1, 3, 'Then tell me the fella''s name playin'' first'),
-- (1, 2, 'Who'),
-- (1, 3, 'The guy playin'' first'),
-- (1, 2, 'That''s his name'),
-- (1, 3, 'Wait…What''s the guy''s name on first base?'),
-- (1, 2, 'What is the guy''s name on second base!'),
-- (1, 3, 'Who''s playin'' second?'),
-- (1, 2, 'Who''s playin'' first'),
-- (1, 3, 'I don''t know'),
-- (1, 2, 'He''s on third base'),
-- (1, 3, 'Look, when you pay off the first baseman every month, who do you pay the money to?'),
-- (1, 2, 'Every dollar of it'),
-- (1, 3, 'Yeah. Look, you gotta pay the money to somebody on first base, don''t you?'),
-- (1, 2, 'Yeah'),
-- (1, 3, 'Does he give you a receipt?'),
-- (1, 2, 'Sure'),
-- (1, 3, 'How does he sign the receipt?'),
-- (1, 2, 'Who'),
-- (1, 3, 'The guy that you give the money to'),
-- (1, 2, 'Who'),
-- (1, 3, 'The guy you give the money to'),
-- (1, 2, 'That''s how he signs it'),
-- (1, 3, 'That''s how who signs it?'),
-- (1, 2, 'Yes'),
-- (1, 3, 'Well go ahead and tell me!?'),
-- (1, 2, 'That''s it'),
-- (1, 3, 'That''s who?'),
-- (1, 2, 'Yeah'),
-- (1, 3, 'When you give the guy the money, doesn''t he have to sign the receipt?'),
-- (1, 2, 'He does!'),
-- (1, 3, 'Well how does he sign his name?'),
-- (1, 2, 'Who'),
-- (1, 3, 'The guy you give the money to'),
-- (1, 2, 'That''s how he signs it!'),
-- (1, 3, 'You! You…You just don''t give money to someone without having ''em sign the receipt!'),
-- (1, 2, 'No! Who signs it'),
-- (1, 3, 'What are you askin'' me for?'),
-- (1, 2, 'Now calm down. I''m not asking you, I am telling you. The…'),
-- (1, 3, 'Well go ahead and tell me. What''s the guy''s name that signs the receipt on first base?'),
-- (1, 2, 'Well now wait a minute. What signs his own receipt'),
-- (1, 3, 'Who signs his own receipt?'),
-- (1, 2, 'No, Who signs his'),
-- (1, 3, 'I''m askin'' you, when the guy on first base gives you a piece of paper…'),
-- (1, 2, 'Yes, now wait…'),
-- (1, 3, '…he puts his name on it'),
-- (1, 2, 'No, Who puts his name on it…'),
-- (1, 3, 'How…'),
-- (1, 2, '…and what puts his name on it…'),
-- (1, 3, 'How does the fella''s name on first base look to you when he signs his name?'),
-- (1, 2, 'Who'),
-- (1, 3, 'To you'),
-- (1, 2, 'That''s how it does'),
-- (1, 3, 'How does it look to you?'),
-- (1, 2, 'Who!'),
-- (1, 3, 'To you'),
-- (1, 2, 'Who!'),
-- (1, 3, 'To you'),
-- (1, 2, 'Who! Look…'),
-- (1, 3, 'When the guy signs his name, how does it look to you?'),
-- (1, 2, 'Now that''s how it looks. Who'),
-- (1, 3, 'How…Who?'),
-- (1, 2, 'Who'),
-- (1, 3, 'I''m askin'' you. What''s the guy''s name on first base you give the money to?'),
-- (1, 2, 'Who! After all, the man''s entitled to it…'),
-- (1, 3, 'Who is?'),
-- (1, 2, 'Yes. Sometimes his wife comes down and collects it'),
-- (1, 3, 'Whose wife?'),
-- (1, 2, 'Yeah, sure'),
-- (1, 3, 'All I''m tryin'' to find out is what''s the guy''s name on first base…'),
-- (1, 2, 'What is on second base'),
-- (1, 3, 'I''m not askin'' you who''s on second'),
-- (1, 2, 'Who''s on first'),
-- (1, 3, 'I don''t know'),
-- (1, 2, 'He''s…'),
-- (1, 3, 'Third base, I know'),
-- (1, 2, 'Yeah'),
-- (1, 3, 'You got a outfield?'),
-- (1, 2, 'Sure'),
-- (1, 3, 'The left fielder''s name?'),
-- (1, 2, 'Why'),
-- (1, 3, 'I just thought I''d ask you'),
-- (1, 2, 'Well I just thought I''d tell you'),
-- (1, 3, 'The left fielder''s name?'),
-- (1, 2, 'Why!?'),
-- (1, 3, 'Hmm…Because!'),
-- (1, 2, 'Oh, he''s center field'),
-- (1, 3, 'Oh…'),
-- (1, 2, 'Told you all these players got…'),
-- (1, 3, 'All I''m tryin'' to figure out is what''s the guy''s name in left field'),
-- (1, 2, 'Now, What''s on second'),
-- (1, 3, 'I''m not askin'' you who''s on second'),
-- (1, 2, 'Who''s on first'),
-- (1, 3, 'I don''t know…'),
-- (1, 2, 'Third base'),
-- (1, 3, 'You got a pitcher on this team?'),
-- (1, 2, 'Wouldn''t be a fine team without a pitcher'),
-- (1, 3, 'What''s his name?'),
-- (1, 2, 'Tomorrow'),
-- (1, 3, 'You don''t want to tell me today?'),
-- (1, 2, 'I''m telling you'),
-- (1, 3, 'Then go ahead'),
-- (1, 2, 'Tomorrow!'),
-- (1, 3, 'What time?'),
-- (1, 2, 'What time what?'),
-- (1, 3, 'What time tomorrow are you gonna tell me who''s pitching?'),
-- (1, 2, 'Now listen. Who is not…'),
-- (1, 3, 'I''ll break your arm, you say who''s on first! I want to know what''s the pitcher''s name?'),
-- (1, 2, 'What''s on second'),
-- (1, 3, 'I don''t know'),
-- (1, 3, 'Third base!'),
-- (1, 3, 'You got a catcher?'),
-- (1, 2, 'Sure'),
-- (1, 3, 'The catcher''s name?'),
-- (1, 2, 'Today'),
-- (1, 3, 'Today. You don''t wanna tell me, today…tomorrow…do you?'),
-- (1, 2, 'I''m telling you'),
-- (1, 3, 'So the catcher''s name?'),
-- (1, 2, 'Today'),
-- (1, 3, 'Today. And Tomorrow''s pitching'),
-- (1, 2, 'Now you''ve got it!'),
-- (1, 3, 'Now I''ve got it…'),
-- (1, 2, 'Hey!'),
-- (1, 3, 'All we got is a couple of days on the team!'),
-- (1, 2, 'Well I can''t help that'),
-- (1, 3, 'All right. You know now, I''m a good catcher. Now, I get behind the plate and…and Tomorrow''s pitching on my team and a heavy hitter gets up'),
-- (1, 2, 'Yes?'),
-- (1, 3, 'Now when he gets up, me being a good catcher, I''m gonna throw the guy out at first base. So the guy bunts the ball. I pick up the ball, I''m gonna throw the guy out at first base. So I pick up the ball and throw it to who?'),
-- (1, 2, 'Now that''s the first thing you''ve said right'),
-- (1, 3, 'I don''t even know what I''m talkin'' about!'),
-- (1, 2, 'Well that''s…That''s all you have…'),
-- (1, 3, 'That''s all I have to do is to throw the ball to first base. Now who''s got it?'),
-- (1, 2, 'Naturally. Now you''ve got it'),
-- (1, 3, 'I throw the ball to first base, somebody''s gotta get the ball! Now who''s got it?'),
-- (1, 2, 'Naturally'),
-- (1, 3, 'Who?'),
-- (1, 2, 'Naturally'),
-- (1, 3, 'Naturally?'),
-- (1, 2, 'Naturally'),
-- (1, 3, 'So I pick up the ball and I throw it to Naturally'),
-- (1, 2, 'No, no, no, no…'),
-- (1, 3, 'He gets the ball. Naturally gets the ball and...'),
-- (1, 2, 'You throw the ball to first base'),
-- (1, 3, 'Then who gets it?'),
-- (1, 2, 'Naturally'),
-- (1, 3, 'So I pick up the ball and I throw it to Naturally'),
-- (1, 2, 'No!'),
-- (1, 3, 'Naturally gets the ball and…and…'),
-- (1, 2, 'You throw the ball to Who'),
-- (1, 3, 'Naturally'),
-- (1, 2, 'Naturally'),
-- (1, 3, 'That''s what I''m saying!?1'),
-- (1, 3, 'I said, I throw the ball to Naturally'),
-- (1, 2, 'No you don''t!'),
-- (1, 3, 'I throw it to who?'),
-- (1, 2, 'Naturally'),
-- (1, 3, 'That''s what I''m saying!'),
-- (1, 2, 'No it isn''t'),
-- (1, 3, 'I throw the ball to first base, somebody''s gotta get it'),
-- (1, 2, 'So Who gets it'),
-- (1, 3, 'Naturally'),
-- (1, 2, 'That''s it'),
-- (1, 3, 'Okay. Now I ask you, who gets it?'),
-- (1, 2, 'Naturally'),
-- (1, 3, 'Same as you!'),
-- (1, 2, 'Now listen…'),
-- (1, 3, 'I throw the ball to Naturally'),
-- (1, 2, 'You throw the ball to Who!'),
-- (1, 3, 'Then who gets it?'),
-- (1, 2, 'Naturally'),
-- (1, 3, 'He better get it! So I throw the ball to first base'),
-- (1, 2, 'All right'),
-- (1, 3, 'Whoever gets it drops the ball and the guy runs to second. Now, Who picks up the ball and throws it to What. What throws it to I Don''t Know. I Don''t Know throws it back to Tomorrow, triple play'),
-- (1, 2, 'Could be'),
-- (1, 3, 'Another guy gets up and hits a long fly ball to Because'),
-- (1, 2, 'Yes'),
-- (1, 3, 'Why? I don''t know! He''s on third and I don''t give a darn!'),
-- (1, 2, 'What''d you say?'),
-- (1, 3, 'I said, I don''t give a darn!'),
-- (1, 2, 'Oh, that''s our shortstop!');
